language: ruby
sudo: false
cache: bundler
rvm:
  - "2.2.9"
  - "2.3.6"
  - "2.4.3"
  - "2.5.0"
  - jruby-9.1.15.0
before_install:
  - gem update bundler
env:
  matrix:
    - EMBER_SOURCE_VERSION="~> 1.0.0" # Uses handlebars-source 1.0.12
    - EMBER_SOURCE_VERSION="~> 1.8.0" # Uses handlebars-source 1.3.0
    - EMBER_SOURCE_VERSION="~> 1.9.0" # Uses handlebars-source 2.0.0
    - EMBER_SOURCE_VERSION="~> 1.10.0" # Uses HTMLBars
    - EMBER_SOURCE_VERSION="~> 1.13.0" # The latest Ember.js 1.x
    - EMBER_SOURCE_VERSION="~> 2.18.0" # The latest Ember.js 2.x
    - EMBER_SOURCE_VERSION="~> 3.0.0.beta.2" # The latest Ember.js 3.x
    - EMBER_SOURCE_VERSION="~> 2.0"
      HANDLEBARS_SOURCE_VERSION="~> 3.0.0" # Uses handlebars-source 3.0.x
    - EMBER_SOURCE_VERSION="~> 2.0"
      HANDLEBARS_SOURCE_VERSION="~> 4.0.0" # Uses handlebars-source 4.0.x
